stages:
  - test
  - report

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test_ui:
  image: python:3.11
  stage: test
  before_script:
    - pip install -r requirements.txt
    - apt-get update && apt-get install -y wget unzip curl chromium chromium-driver default-jre
    - wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
    - unzip allure-2.29.0.zip -d /opt/
    - export PATH=$PATH:/opt/allure-2.29.0/bin
  script:
    - pytest --alluredir=reports/allure-results
  artifacts:
    paths:
      - reports/allure-results
    expire_in: 1 week

allure_report:
  stage: report
  image: openjdk:11
  script:
    - /opt/allure-2.29.0/bin/allure generate reports/allure-results -o reports/allure-report --clean
  artifacts:
    paths:
      - reports/allure-report
    expire_in: 1 week
